name: peliculas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.6
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter_native_splash:
  background_image: "assets/images/background_app_splash_image.jpg"
  android_12:
    image: "assets/icons/peliculas_app_launcher_icon.jpg"
    ios: true
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/peliculas_app_launcher_icon.jpg"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/